from fastapi import APIRouter, HTTPException, UploadFile, File, Form
from pydantic import BaseModel
from typing import Optional, Dict, Any
from app.services.gemini import gemini_service

router = APIRouter()

class AnswerRequest(BaseModel):
    query: str

class SafetyRequest(BaseModel):
    text: str

class EmbeddingRequest(BaseModel):
    text: str

class TranslateRequest(BaseModel):
    text: str
    target_language: str

@router.post("/answer")
async def generate_answer(request: AnswerRequest):
    """
    Generate an agricultural answer in Tamil using Gemini.
    """
    try:
        answer = await gemini_service.generate_answer(request.query)
        return {"answer": answer}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/safety-check")
async def check_safety(request: SafetyRequest):
    """
    Check if text is safe agricultural knowledge.
    """
    try:
        result = await gemini_service.check_safety(request.text)
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/embed/document")
async def embed_document(request: EmbeddingRequest):
    """
    Generate Document Embedding.
    """
    try:
        embedding = await gemini_service.generate_document_embedding(request.text)
        if embedding is None:
            raise HTTPException(status_code=500, detail="Failed to generate embedding")
        return {"embedding": embedding}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/embed/query")
async def embed_query(request: EmbeddingRequest):
    """
    Generate Query Embedding.
    """
    try:
        embedding = await gemini_service.generate_query_embedding(request.text)
        if embedding is None:
            raise HTTPException(status_code=500, detail="Failed to generate embedding")
        return {"embedding": embedding}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/translate")
async def translate_text(request: TranslateRequest):
    """
    Translates text to target language via Gemini.
    """
    try:
        translated = await gemini_service.translate_text(request.text, request.target_language)
        return {"translated_text": translated}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/analyze-crop")
async def analyze_crop(
    file: UploadFile = File(...),
    query: str = Form("")
):
    """
    Analyzes an uploaded crop image with an optional query for disease diagnosis.
    Returns a JSON string matching the agreed upon structure.
    """
    try:
        image_bytes = await file.read()
        analysis = await gemini_service.analyze_crop_disease(image_bytes, query)
        # Returns the raw JSON string generated by Gemini to let the Flutter app parse it
        return {"analysis": analysis}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
